<?php

$title = 'Delete Query Count';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="alert alert-error">
  <strong>Danger!</strong> Deleting this resource will also remove any dependent monitoring plans (which will also remove any alert subscriptions tied to those plans.)
</div>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->queryCount->name); ?>'?
</p>
<?php
$url = $this->url('queries', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->queryCount->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>