<?php

$title = 'Query: ' . $this->escapeHtml($this->queryCount->name);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="well">
    <dl>
      <dt><h4>DB Connection</h4></dt>
      <dd><?php echo $this->dbConnectionName($this->queryCount->which_db);?></dd>
      <dt><h4>Query</h4></dt>
      <dd><pre><?php echo $this->escapeHtml($this->queryCount->query); ?></pre></dd>
      <dt><h4>Fail Count</h4></dt>
      <dd><?php echo $this->escapeHtml($this->queryCount->fail_count); ?></dd>
    </dl>
</div>

<h3>Status Check History</h3>
<table class="table table-striped table-bordered">
<tr>
    <th>Date Checked</th>
    <th>Result</th>
    <th>Error Details</th>
</tr>
<?php foreach ($this->statusChecks as $statusCheck) : ?>
<tr>
    <td><?php echo $this->date($statusCheck->datetime_checked);?></td>
    <td><?php echo $this->boolResult($statusCheck->success);?></td>
    <td>
        <pre><?php echo $this->escapeHtml($statusCheck->error_details);?></pre>
    </td>
</tr>
<?php endforeach; ?>
</table>