<?php

use Application\Model\FrequencyUnit;

$title = 'Plan: ' . $this->escapeHtml($this->monitoringPlan->name);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="well">
    <dl>
      <dt><h4>Resource</h4></dt>
      <dd><?php echo $this->resourceName($this->monitoringPlan->resource_id); ?></dd>
      <dt><h4>Execution Days</h4></dt>
      <dd>
        <?php if ($this->monitoringPlan->run_mondays) echo 'M'; ?>
        <?php if ($this->monitoringPlan->run_tuesdays) echo 'T'; ?>
        <?php if ($this->monitoringPlan->run_wednesdays) echo 'W'; ?>
        <?php if ($this->monitoringPlan->run_thursdays) echo 'R'; ?>
        <?php if ($this->monitoringPlan->run_fridays) echo 'F'; ?>
        <?php if ($this->monitoringPlan->run_saturdays) echo 'S'; ?>
        <?php if ($this->monitoringPlan->run_sundays) echo 'U'; ?>
      </dd>
      <dt><h4>Frequency</h4></dt>
      <dd>
        <?php
            switch ($this->monitoringPlan->frequency_unit) {
                case FrequencyUnit::MINUTE:
                    $unit = 'minute(s)';
                    break;
                case FrequencyUnit::HOUR:
                    $unit = 'hour(s)';
                    break;
                case FrequencyUnit::DAY:
                    $unit = 'day(s)';
                    break;
            }
            echo sprintf('Every %d %s', $this->monitoringPlan->frequency, $unit);
        ?>
      </dd>
      <dt><h4>Execution Time</h4></dt>
      <dd>
        <?php echo $this->time($this->monitoringPlan->starting_at);?> - 
        <?php echo $this->time($this->monitoringPlan->ending_at);?>
      </dd>
    </dl>
</div>

<h3>Status Check History</h3>
<table class="table table-striped table-bordered">
<tr>
    <th>Date Checked</th>
    <th>Result</th>
    <th>Error Details</th>
</tr>
<?php foreach ($this->statusChecks as $statusCheck) : ?>
<tr>
    <td><?php echo $this->date($statusCheck->datetime_checked);?></td>
    <td><?php echo $this->boolResult($statusCheck->success);?></td>
    <td>
        <pre><?php echo $this->escapeHtml($statusCheck->error_details);?></pre>
    </td>
</tr>
<?php endforeach; ?>
</table>