<?php

$title = 'Add new SOAP Service';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('soapservices', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('name'));
//echo $this->formRow($form->get('wsdl_location'));
//echo $this->formSubmit($form->get('submit'));
echo $this->formCollection($form);
echo $this->form()->closeTag();