<div class="well">
    <h2>Welcome!</h2>
    <p>Resource Monitor is a web-based tool designed to keep an eye on resources such as database connections, SOAP services, and query results. It is designed to be run internally at your organization so that credentials and other sensitive data don't have to leave your network and get stored somewhere in the "cloud."</p>
    <p>If you haven't already, you can get up and running easily by:</p>
    <ul>
        <li>Creating resources such as <a href="<?php echo $this->url('soapservices');?>">SOAP services</a>, <a href="<?php echo $this->url('dbconnections');?>">database connections</a>, or <a href="<?php echo $this->url('queries');?>">queries</a>.</li>
        <li>Pinning those resources to <a href="<?php echo $this->url('plans');?>">monitoring plans</a>.</li>
        <li>Adding <a href="<?php echo $this->url('alerts');?>">alert subscriptions</a> so stakeholders can be notified as soon as a problem is detected.</li>
    </ul>
    <p>That's it! Once you've got your monitoring plans configured how you want them, Resource Monitor will keep an eye on all of your assets as frequently as you defined them.</p>
</div>
